set softtabstop=2
set smartindent

" Enable colorscheme
colorscheme gruvbox

" Airline & theming it
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'
let g:airline_theme='gruvbox'
